### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by darkspeaker** [darkspeaker/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by garnuyHid** [comment]
`[Trump's political positions have been described as populist, protectionist, isolationist, and nationalist. He entered the 2016 presidential race as a Republican and was elected in an upset victory over Democratic nominee Hillary Clinton while losing the popular vote.[a] He was the first U.S. president without prior military or government service. His election and policies sparked numerous protests. Trump made many false and misleading statements during his campaigns and presidency, to a degree unprecedented in American politics. Many of his comments and actions have been characterized as racially charged or racist.](url)`

**Comment by garnuyHid** [comment]
I'M THE 45TH PRESIDENT OF THE UNITED STATES

**Comment by garnuyHid** [comment]
<h2>RESUME</h2>
<h3>I AM THE 45TH PRESIDENT OF THE UNITED STATES</h3>
<p>I’m the most successful person ever to run for the presidency, by far. Nobody’s ever been more successful than me. I’m the most successful person ever to run. Ross Perot isn’t successful like me. Romney—I have a Gucci store that’s worth more than Romney.</p>
