### ISSUE TITLE
Скласти блок контактної інформації

### ISSUE THREAD

**Issue by darkspeaker** [darkspeaker/homepage#5]
Посилання на соцмережі (Facebook чи Instagram, тощо), номер телефону чи адреса електронної скриньки, тощо. Може не всі лінки в світі, а тільки ті, що дійсно доречні.

**Comment by garnuyHid** [comment]
[https://www.instagram.com/realdonaldtrump/](url)
[https://twitter.com/donaldtrump](url)
[https://www.facebook.com/DonaldTrump/](url)
[https://www.facebook.com/officialteamtrump](url)
