### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by darkspeaker** [darkspeaker/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by garnuyHid** [comment]
### Ранній успіх (1968—1989)
Трамп почав свою кар'єру в батьковій компанії і спочатку зосередився на царині діяльності, яка була пріоритетною для його батька, — оренді будинків для людей, які належать до середнього класу, у Брукліні, Квінсі та Стейтен-Айленді. Одним із перших Дональдових проєктів (він іще вчився в коледжі) була модернізація заставленого без права викупу 1200-квартирного комплексу в Цинциннаті, штат Огайо, «Свіфтон-Віллидж». Там не зданими в оренду числилися 66 % квартир, тоді як Трамп за допомогою свого проєкту мав на меті реалізувати 100 % протягом року. Коли Trump Organization продала «Свіфтон-Віллидж» за $12 млн, компанія отримала $6 млн чистого прибутку.

1971 року Трамп переїхав на Мангеттен. Тут він побачив економічні можливості міста, особливо в плані великих будівельних проєктів на Мангеттені, які передбачали отримання високого прибутку завдяки архітектурному проєктуванню. Такі проєкти видавалися дуже престижними й сприяли суспільному визнанню. Спочатку Трамп став домагатися права забудови старих пенсильванських центральних станцій у Вест-Сайді, згодом із залученням 40-річної податкової знижки — з фінансового погляду перевищеної урядом Нью-Йорка, який вирішив дати податкову пільгу в обмін на інвестиції під час фінансової кризи в готель «Комодор», який став банкрутом, щоб зробити з нього новий готель «Ґранд-Гаятт».

Трамп також був пов'язаний із будівництвом Конференц-центру Джейкоба Джевітса, оскільки був власником землі, на якій того будували. Будівництво Конференц-центру Джейкоба Джевітса призвело до розбіжностей між Трампом та урядом Нью-Йорка: Трамп оцінював цей проєкт в $110 млн, у той час як підрахунки міста виводили цифру від $750 млн до $1 млрд. Трамп запропонував контролювати вартість проєкту в межах тієї суми, яка вийшла в нього, але цю пропозицію не було ухвалено.

Схожа ситуація виникла при спробі міста оновити ковзанку Воллмен-Ринк у Центральному парку. Проєкт, розрахований на 2,5 роки будівельних робіт, розпочато 1980 року. Проте, витративши на нього $12 млн, місто так і не завершило його навіть до 1986 року. Трамп запропонував безкоштовно взяти об'єкт на свій баланс з метою продовжити роботу за свої гроші, але йому відмовили, що стало темою для місцевих ЗМІ. Тож урешті Трамп таки отримав дозвіл на будівництво, яке закінчив за шість місяців, заощадивши при цьому $750 тисяч із закладених у бюджеті $3 млн.

### Фінансові труднощі (1989—1997)

Трамп брався за дедалі амбіційніші проєкти, але з 1989 року через фінансову кризу не мав змоги вчасно погашати взяті позики. У будівництво свого третього казино «Трамп-Тадж-Махал» він вклав $1 млрд — переважно високовідсотковими «неперспективними облігаціями». Таке рішення дало йому перевагу над конкурентами, які використовували більшу частину власних грошей для фінансування своїх проєктів. Незважаючи на те, що Трамп зміцнив позиції свого бізнесу додатковими позиками й відтермінованими платежами відсотків, борги, що далі зростали до 1991 року, стали причиною не тільки банкрутства, пов'язаного з бізнесом, але й поставили його на межу особистого банкрутства. Банки й власники облігацій утратили сотні мільйонів доларів, але все ж вирішили реструктурувати Трампів борг, щоб уникнути ще більшої витрати грошей у суді. Казино «Трамп-Тадж-Махал» було звільнено від стану банкрутства 5 жовтня 1991 року, коли Трамп передав 50 % своєї частки початковим власникам облігацій в обмін на знижену відсоткову ставку боргу та збільшення часу для виплат.

2 листопада 1992 року керівництво готелю «Трамп-Плаза, Атлантик-Сіті» змусило Трампа подати план захисту «підготовленого банкрутства» згідно з розділом 11 Кодексу про банкрутство США після того, як він не зміг виплачувати борг. За планом, Трамп погодився поступитися 49 % своєї частки в п'ятизірковому готелі «Сітібанк» і п'яти іншим кредиторам. У свою чергу, Трамп отримав вигідніші умови для виплат за позиками, узятих у кредиторів, на більш ніж $550 млн і зберіг свою посаду виконавчого директора, незважаючи на те, що нічого не виплачував й не брав участі в роботі готелю.

До 1994 року Трамп погасив велику частину свого особистого боргу в $900 млн і значно зменшив боргові зобов'язання в бізнесі — близько $3,5 млрд. Хоча він був змушений відмовитися від авіакомпанії Trump Shuttle (яку купив 1989 року), проте йому вдалося зберегти Трамп-тауер у Нью-Йорку й залишитися керівником трьох казино в Атлантик-Сіті. Банк «Чейз Мангеттен», що надав Трампові кредит на купівлю будмайданчиків Вестсайда (його найбільшої частки на Мангеттені), був змушений продати цю частину азійським забудовникам.

1995 року Трампа було обрано до «Gaming Hall of Fame».

Того самого 1995 року Трамп об'єднав свої казино у відкриту акціонерну компанію Trump Hotels & Casino Resorts. 1996 року ціни акцій компанії на Уолл-стріт перевищили $35, проте вже 1998 року впали нижче $10, оскільки компанія залишалася нерентабельною, і їй заледве вдавалося оплачувати відсотки за боргом у майже $3 млрд. При такому важкому фінансовому становищі у Трампа не було можливості перебудовувати об'єкти, які входили в його групу, аби ті не відставали від своїх «глянцевих» суперників.

Кінець кінцем, 21 жовтня 2004 року компанія Trump Hotels & Casino Resorts повідомила про реструктуризацію боргу[20]. План зобов'язував Трампа зменшити свою частку з 56 % до 27 % й віддати облігаціонерам акції в обмін на відмову від частини боргу. З того часу Trump Hotels змушена була шукати захист від добровільного банкрутства, щоб залишитися на плаву. Після того, як компанія звернулася до розділу 11 Кодексу про банкрутство США в листопаді 2004 року, Трамп відмовився від посади генерального директора, але залишився головою ради директорів. У травні 2005 року компанія знову почала працювати, але вже під назвою Trump Entertainment Resorts Holdings.

### Відродження бізнесу (1997—2007)
З кінця 1990-х років Трамп працював над кількома проєктами, етапи розвитку яких були різні.

Будівництво хмарочоса «Міжнародний готель і вежа Трампа — набережна Вайкікі-Біч» здавалося перспективним. За словами Трампа, покупці робили внески, які не підлягають рефінансуванню, щоб одразу ж купити площу, щойно це стане можливим. Спорудження будинку «Міжнародний готель і вежа Трампа — Чикаго» тривало за планом, незважаючи на те, що 30 % площі не було продано. З невеликим відставанням будували «Міжнародний готель і вежа Трампа — Торонто». Менш удалим виявилося будівництво «Трамп-тауер — Тампа»: занадто великий попит викликав суперечки про перегляд цін на площі в бік підвищення. За три роки після початку цього будівництва його припинили, унаслідок чого покупці подали позови. У Форт-Лодердейлі, штат Флорида, один проєкт будівництва змусив чекати схвалення іншого — будівництва будівлі «Міжнародний готель і вежа Трампа — Форт-Лодердейл». «Трамп-тауерс — Атланта» — ринок житла, який має другу позицію в Національному реєстрі непроданих будинків.

На президентських виборах 2000 року Трамп узяв участь у праймеріз від партії Реформ.
