### ISSUE TITLE
Скласти додаткові інформаційні блоки

### ISSUE THREAD

**Issue by darkspeaker** [darkspeaker/homepage#7]
Можна зробити резюме менш формальним, додавши додаткові блоки, які містять корисну інформацію, але подають її в "розважальній" формі. Наприклад, що подобається і не подобається, сильні і слабкі сторони, перелік навиків чи хобі, інфографіка або ж інтерактивні модулі, тощо. Варто написати контент такого блоку раніше, ніж починати верстку, бо його розміри впливатимуть на розміщення елементів на сторінці.

**Comment by garnuyHid** [comment]
### Ліцензування імені
Та незважаючи на певні труднощі, Трампів бізнес у галузі нерухомості загалом був надзвичайно успішним, так що Трамп навіть ліцензував власне ім'я, під яким утілювалися будівельні проєкти. Багато забудовників платять Дональду Трампу за те, щоб він продавав їхню нерухомість і був «обличчям» їхніх проєктів. Із цієї причини багато будівель з іменем Трампа не є його власністю. За даними журналу «Forbes», ця частина імперії Трампа, якою насправді керують його діти, є найціннішою — не менше $562 млн. За інформацією «Forbes», існують 33 ліцензійні проєкти в стадії будівництва, зокрема сім «готелів-кондомініумів» (наприклад, «The seven Trump International Hotel and Tower developments»). Проте після антимусульманських заяв Трампа в ході передвиборчої президентської кампанії турецький власник «Trump Towers Istanbul», який платив Трампові за використання його імені, вирішив удатися до юридичних кроків з метою розірвання угоди з Трампом.

### Хобі
Трамп — завзятий гравець у гольф. Він є членом клубу «Winged Foot Golf Club» у Мамаронеку, штат Нью-Йорк, а також регулярно бере участь у змаганнях на своїх майданчиках
